### PR TITLE
Updated the date format

### PR DESCRIPTION
**Pull request by 9Y0**
The date format looks like "2017-02-24T17:19:18+00:00". I deleted the T form the time string, because the T char is not allowed in the DateFormat.

### CODE REVIEW

**Comment by hugmanrique** [comment]
Have you tested if the new format works?

**Comment by 9Y0** [comment]
Yes. I got some dates using the Web API and tested if they worked and it I didn't got weird results.

**Comment by 9Y0** [comment]
The date is formatted this way: 2017-02-25T8:38:25+00:00

**Comment by hugmanrique** [comment]
Thanks!

**Pull request merged**
